name: deploy

on:
  push:
    branches:
      - main
   

jobs:
  deployment:
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build the Docker image
        run: |
          docker buildx create --use
          docker buildx inspect --bootstrap
          docker buildx build --platform linux/amd64,linux/arm64 -t ${{secrets.DOCKER_USERNAME}}/docsync:latest -f ./server/docker/Dockerfile ./server

      
      - name: build and push docker images
        run: |
          
         
         
          docker images
          docker login -u ${{secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker push ${{secrets.DOCKER_USERNAME}}/docsync 

      - name: setup ssh
        run: |
          mkdir ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" >> ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -t rsa 54.167.223.77 >> ~/.ssh/known_hosts
          scp -i ~/.ssh/id_rsa docker-compose.yaml ubuntu@54.167.223.77: 
          ssh -i ~/.ssh/id_rsa ubuntu@54.167.223.77 "docker pull rrrronit/docsync && docker-compose up -d"
