name: deploy

on:
  push:
    branches:
      - main
    path: 
      - server/*
   

jobs:
  deployment:
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build the Docker image
        run: |
      
          
          docker login -u ${{secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker buildx build -t ${{secrets.DOCKER_USERNAME}}/docsync:latest -f ./server/docker/Dockerfile ./server --push

  
      - name: setup ssh
        run: |

          mkdir ~/.ssh

          touch .env
          echo "REDIS_URL=${{secrets.REDIS_URL}}" >> .env
          echo "DATABASE_URL=${{secrets.DATABASE_URL}}" >> .env
          echo "REDIS_TOKEN=${{secrets.REDIS_TOKEN}}" >> .env

          echo "${{ secrets.SSH_PRIVATE_KEY }}" >> key.pem
          chmod 600 key.pem
          ssh-keyscan -t rsa ec2-54-226-83-195.compute-1.amazonaws.com >> ~/.ssh/known_hosts
          
          scp -i key.pem .env server/docker-compose.yaml ubuntu@ec2-54-226-83-195.compute-1.amazonaws.com: 
          ssh -i key.pem ubuntu@ec2-54-226-83-195.compute-1.amazonaws.com "sudo docker pull ${{secrets.DOCKER_USERNAME}}/docsync:latest && sudo docker kill $(sudo docker ps -qa) || true && sudo docker-compose up -d"
